---
AWSTemplateFormatVersion: '2010-09-09'

Description: |
  The following CloudFormation Okta resource types allow the creation and configuration of
  Applications, Groups, Policies and associated memberships. This allows you to onboard new applications
  simply, efficiently, and consistently.

Resources:
  NewOktaApp:
    Type: Okta::Application::Application
    Properties:
      Name: "template_basic_auth"
      Label: "CFN Sample Application"
      SignOnMode: "BASIC_AUTH"
      Settings:
        App:
          Url: "https://example.com/login.html"
          AuthURL: "https://example.com/auth.html"

  NewOktaGroup:
    Type: Okta::Group::Group
    Properties:
      Profile:
        Name: CFN Sample Group
        Description: Description of the CFN Sample Group

  NewGroupAssociation:
    Type: Okta::Group::GroupApplicationAssociation
    Properties:
      ApplicationId: 0oa1d6uujxz48JnNu697
      GroupId: 00g1e6z3hj56cYK7c697

  NewGroupUserMembership:
    Type: Okta::Group::Membership
    Properties:
      GroupId: 00g1e6z3hj56cYK7c697
      UserLogin: okta@nakomis.com
