---
AWSTemplateFormatVersion: '2010-09-09'

Description: |
  The following CloudFormation Okta resource types allow the creation and configuration of
  Applications, Groups, Policies and associated memberships. This allows you to onboard new applications
  simply, efficiently, and consistently.

Resources:
  NewGroupAssociation:
    Type: Okta::Group::GroupApplicationAssociation
    Properties:
      ApplicationId: 0oa1d6uujxz48JnNu697
      GroupId: 00g1e6z3hj56cYK7c697

  NewGroupMembership:
    Type: Okta::Group::Membership
    Properties:
      GroupId: 00g1e6z3hj56cYK7c697
      UserIdentifier:
        Login: okta@nakomis.com
