version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Entered the install phase...
      - echo About to build $RESOURCE_PATH
      - export PATH="/usr/local/bin:$PATH"
      - /usr/local/bin/dockerd-entrypoint.sh
      - cat /var/log/docker.log
      - cd $RESOURCE_PATH
      - python get_type_configuration.py
      - npm --version
      - node --version

  build:
    commands:
      - echo Entered the build phase...
      - cfn validate
      - cfn generate
      - ./setup.sh
      - cfn submit --dry-run
      - nohup sam local start-lambda &
      - sleep 10
      - cfn test
    finally:
      - cat rpdk.log
      - ./cleanup.sh
artifacts:
  files:
    - $BUILD_FILE_NAME 
  name: extensions-build

