version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Entered the install phase...
      - echo About to build $RESOURCE_PATH
      - export PATH="/usr/local/bin:$PATH"
      - /usr/local/bin/dockerd-entrypoint.sh
      - cat /var/log/docker.log
      - cd $RESOURCE_PATH
      - pwd
      - ls

  build:
    commands:
      - echo Entered the build phase...
      - ./deregister-all.sh us-east-1
      - ./publish.sh us-east-1
      - ./release/deregister-all.sh us-west-2
      - ./publish.sh us-west-2

